line-length = 120

[format]
docstring-code-format = true

[lint]
select = ["ALL"]
ignore = [
    "D1",    # undocumented
    "D203",  # one blank line before class
    "D213",  # multi-line summary second line
    "TD001", # invalid todo tag
    "TD002", # missing todo author
    "TD003", # missing todo link
    "PD011", # pandas use of dot values
]
unfixable = [
    "F401",
    "F841",
]
pydocstyle.convention = "google"

[lint.per-file-ignores]
"tests/**/*.py" = [
    "D",
    "S101",
    "N802",
    "ARG",
]
"config/**/*.py" = ["ALL"]
"manage.py" = ["ALL"]
"**/migrations/*.py" = ["ALL"]

[lint.pylint]
max-args = 6